# Generated by Django 5.1.6 on 2025-09-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_creation', models.DateField()),
                ('description_probleme', models.TextField()),
                ('donnees_utilisees', models.TextField()),
                ('etapes_resolution', models.TextField(help_text="Décrivez les étapes du projet, de la préparation des données à l'évaluation du modèle.")),
                ('resultats_modeles', models.TextField(help_text='Liste des résultats pour chaque modèle utilisé (métriques, précisions, etc.).')),
                ('lecons_apprises', models.TextField()),
                ('ameliorations_possibles', models.TextField()),
                ('lien_code', models.URLField(blank=True, help_text='Lien vers le dépôt GitHub ou Google Colab du projet.', null=True)),
            ],
            options={
                'verbose_name_plural': 'projects',
                'ordering': ['-date_creation'],
            },
        ),
    ]
