# Generated by Django 5.1.6 on 2025-09-03 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ameliorations_possibles',
        ),
        migrations.RemoveField(
            model_name='project',
            name='etapes_resolution',
        ),
        migrations.RemoveField(
            model_name='project',
            name='lecons_apprises',
        ),
        migrations.RemoveField(
            model_name='project',
            name='resultats_modeles',
        ),
        migrations.CreateModel(
            name='AmeliorationPossible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ameliorations', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='EtapeResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='LeconApprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_modele', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_modeles', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Metrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('valeur', models.CharField(help_text="Ex: '92.5%', '0.85', '125 ms'", max_length=100)),
                ('resultat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metriques', to='projects.resultatmodele')),
            ],
        ),
    ]
