# Generated by Django 5.1.6 on 2025-09-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_ameliorations_possibles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='donnees_utilisees',
            field=models.TextField(blank=True, null=True),
        ),
    ]
