# Generated by Django 5.1.6 on 2025-09-03 17:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_justification_project_objective_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ameliorationpossible',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etaperesolution',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leconapprise',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metrique',
            name='valeur',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_probleme',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='donnees_utilisees',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='justification',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='objective',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
