# Generated by Django 5.1.6 on 2025-09-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_resultatmodele_resultats_conclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='capture',
            field=models.ImageField(blank=True, help_text="Capture d'écran ou image principale du projet.", null=True, upload_to='project_captures/'),
        ),
    ]
