# Generated by Django 5.1.6 on 2025-09-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_alter_experience_certification_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='certification_file',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
