# Generated by Django 5.1.6 on 2025-09-11 11:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='about/')),
                ('presentation', ckeditor.fields.RichTextField()),
                ('professional_evolution', ckeditor.fields.RichTextField()),
                ('vision', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
