# Generated by Django 5.1.6 on 2025-09-11 11:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='about/photos/'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='presentation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='professional_evolution',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='vision',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
